# Generated by Django 5.2.3 on 2025-06-30 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirukbilugTracker',
            fields=[
                ('BirukBilugID', models.AutoField(primary_key=True, serialize=False)),
                ('municipality', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('boat_id', models.AutoField(primary_key=True, serialize=False)),
                ('boat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('boat_type', models.CharField(max_length=50)),
                ('built_place', models.CharField(max_length=100)),
                ('built_year', models.IntegerField()),
                ('material_used', models.CharField(max_length=100)),
                ('registered_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registered_breadth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registered_depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boat_image', models.ImageField(blank=True, null=True, upload_to='boat_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalAgriculturist',
            fields=[
                ('municipal_agriculturist_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('municipality', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvincialAgriculturist',
            fields=[
                ('provincial_agriculturist_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'unique': 'A user with this username already exists.'}, max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email address already exists.'}, max_length=254, unique=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('provincial_agriculturist', 'Provincial Agriculturist'), ('municipal_agriculturist', 'Municipal Agriculturist')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('municipal_agriculturist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.municipalagriculturist')),
                ('provincial_agriculturist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.provincialagriculturist')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('logId', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fisherfolk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fisherfolk_number', models.CharField(max_length=50, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('appelation', models.CharField(blank=True, max_length=20, null=True)),
                ('civil_status', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('schedule', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('fishery_section', models.CharField(max_length=100)),
                ('fishing_ground', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='fisherfolk_pictures/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_fisherfolk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FisherfolkBoat',
            fields=[
                ('boat_registry_no', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_ownership', models.CharField(max_length=50)),
                ('no_of_fishers', models.IntegerField()),
                ('homeport', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('BirukBilugID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.birukbilugtracker', unique=True)),
                ('boat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.boat')),
                ('fisherfolk_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fisherfolk')),
            ],
        ),
        migrations.CreateModel(
            name='BoatBirukbilugTracker',
            fields=[
                ('TrackingNo', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('BirukBilugID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.birukbilugtracker')),
                ('BoatRegistryNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fisherfolkboat')),
            ],
        ),
        migrations.AddConstraint(
            model_name='fisherfolk',
            constraint=models.UniqueConstraint(fields=('first_name', 'middle_name', 'last_name', 'birth_date'), name='unique_fisherfolk_identity'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('username',), name='unique_username_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email',), name='unique_email_case_insensitive'),
        ),
    ]
